# Generated by Django 5.0.14 on 2026-06-06 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_grupoprivado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigCampeao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definido_em', models.DateTimeField(auto_now=True)),
                ('campeao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_campeao', to='api.time', verbose_name='Time Campeão')),
            ],
            options={
                'verbose_name': 'Configuração do Campeão',
                'verbose_name_plural': 'Configuração do Campeão',
            },
        ),
        migrations.CreateModel(
            name='PalpiteCampeao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites_campeao', to='api.time')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='palpite_campeao', to=settings.AUTH_USER_MODEL)),
            ],
        ),

    ]
