# Generated by Django 5.0.14 on 2026-06-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_configcampeao_palpitecampeao'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='posicao',
            field=models.IntegerField(blank=True, help_text='Posição no chaveamento (ex: 1..16 nos 16 avos). Usado para ordenar o bracket.', null=True),
        ),
    ]
